inventory = []

item = input("Please enter quantity: ")
inventory.append(int(item))
print(inventory)
item = input("Please enter quantity: ")
inventory.append(int(item))
print(inventory)
item = input("Please enter quantity: ")
inventory.append(int(item))
print(inventory)
item = input("Please enter quantity: ")
inventory.append(int(item))
print(inventory)
item = input("Please enter quantity: ")
inventory.append(int(item))
print(inventory)
item = input("Please enter quantity: ")
inventory.append(int(item))
print(inventory)
item = input("Please enter quantity: ")
inventory.append(int(item))
print(inventory)
item = input("Please enter quantity: ")
inventory.append(int(item))
print(inventory)
item = input("Please enter quantity: ")
inventory.append(int(item))
print(inventory)
item = input("Please enter quantity: ")
inventory.append(int(item))
print(inventory)
